[package]
name = "AEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type=['rlib']

[dependencies]
gl="0.14.0"
glfw="0.44.0"
image="0.20.1"